#!/bin/bash
# Check if the scp command was successful
if [ "$#" -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/

if [ $? -eq 0 ]; then
  echo "File transfer successful!"
else
  echo "File transfer failed!"
fi
