#!/bin/bash
# Update package lists
apt-get update

apt-get install -y nginx

# Configure Nginx to listen on port 80
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

service nginx restart

echo "Hello World!" > /var/www/html/index.html
