#!/usr/bin/env bash
# Steps to set up Nginx on Web-Sever-01

# Updating Packages before making Installations
sudo apt-get update
sudo apt-get -y install nginx

# Setting up the UFW firewall to let Nginx HTTP traffic in
sudo ufw allow 'Nginx HTTP'

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Checking if Nginx settings are free of errors
sudo nginx -t

# Restarting Nginx
sudo service nginx start
