#!/usr/bin/env bash
#  sets up a new Ubuntu machine to redirect all incoming requests to another web address.

# Refreshing or updating packages prior to installation
sudo apt-get update
sudo apt-get install -y nginx

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Performing a 301 Redirection
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/mlu1432 permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restarting Nginx service
sudo service nginx restart
