#!/usr/bin/env bash
# Configures a new Ubuntu machine by installing Nginx.
# Nginx will listen on port 80 and serve a "Hello World" page,
# along with redirecting a specific path to a LinkedIn profile.

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
     sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# Starting nginx service
sudo service nginx start

# Allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# Setting up /redirect_me to your LinkedIn profile
sudo sed -i '24i\	rewrite ^/redirect_me https://www.linkedin.com/in/lucas-sekwati-723029bb/ permanent;' /etc/nginx/sites-available/default

# Set up a 404 page
echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default

# Restarting nginx
sudo service nginx restart

echo -e "\nCompleted.\n"
