#!/usr/bin/env bash
# duplicate web-01 to web-02
#set -x
# Script to install Nginx and configure it with a custom HTTP header

echo -e "Updating and doing some minor checks...\n"

function install() {
	command -v "$1" &> /dev/null

	#shellcheck disable=SC2181
	if [ $? -ne 0 ]; then
		echo -e "Installing: $1\n"
		sudo apt-get update -y -qq && \
			sudo apt-get install -y "$1" -qq
		echo -e "\n"
	else
		echo -e "$1 is already installed.\n"
	fi
}

install nginx # Install Nginx

echo -e "\nSetting up some minor stuff.\n"

# Allowing Nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
if [ -d "/var/www" ]; then
	sudo chown -R "$USER":"$USER" /var/www
	sudo chmod -R 755 /var/www
else
	sudo mkdir -p /var/www
	sudo chown -R "$USER":"$USER" /var/www
	sudo chmod -R 755 /var/www
fi

# Create directories if not present
for dir in /var/www/{html,error}; do
	if ! [ -d "$dir" ]; then
		mkdir -p "$dir"
	fi
done

# Create new index
echo "Hello World!" > /var/www/html/index.html

# Create new error page
echo "Ceci n'est pas une page" > /var/www/html/error_404.html

# Backup default server config file
sudo cp /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/default.backup

server_config="
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;

	server_name _;

	location / {
		add_header X-Served-By \$hostname;
		try_files \$uri \$uri/ =404;
	}

	location /redirect_me {
		return 301 https://www.linkedin.com/in/lucas-sekwati-723029bb/;
	}

	error_page 404 /error_404.html;
	location = /error_404.html {
		internal;
	}
}
"

#shellcheck disable=SC2154
echo "$server_config" | sudo tee /etc/nginx/sites-enabled/default > /dev/null

# Restart Nginx to apply changes
if [ "$(pgrep -c nginx)" -le 0 ]; then
	sudo service nginx start
else
	sudo service nginx restart
fi

echo -e "\nNginx has been installed and configured.\n"

