#!/usr/bin/env bash
# Update package list
# Script to install and configure HAProxy on the load balancer

echo "Updating package list and installing HAProxy..."

# Update package list
sudo apt-get update -y

# Install HAProxy
sudo apt-get install -y haproxy

# Enable HAProxy to start at boot
sudo systemctl enable haproxy

# Set up HAProxy configuration
echo "Configuring HAProxy..."

sudo tee /etc/haproxy/haproxy.cfg > /dev/null << EOF
global
	log /dev/log    local0
	log /dev/log    local1 notice
	chroot /var/lib/haproxy
	stats socket /run/haproxy/admin.sock mode 660 level admin
	stats timeout 30s
	user haproxy
	group haproxy
	daemon

defaults
	log     global
	mode    http
	option  httplog
	option  dontlognull
	timeout connect 5000
	timeout client  50000
	timeout server  50000

frontend http_front
	bind *:80
	default_backend http_back

backend http_back
	balance roundrobin
	server web01 100.26.156.194:80 check
	server web02 3.94.213.104:80 check

listen stats
	bind *:8404
	mode http
	stats enable
	stats uri /haproxy?stats
	stats hide-version
	stats auth admin:admin
EOF

# Restart HAProxy to apply changes
sudo systemctl restart haproxy

# Verify HAProxy configuration
echo "Verifying HAProxy configuration..."
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Confirm HAProxy status
sudo systemctl status haproxy

echo "HAProxy has been installed and configured."
