#!/usr/bin/env bash
# install and configure HAProxy on lb-01 server.


sudo apt update
sudo apt install -y haproxy

sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOL
global
    log /dev/log local0
    log /dev/log local1 notice
    maxconn 2000
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend  mlu1432_frontend
        bind *:80
        mode http
        default_backend mlu1432_backend

backend mlu1432_backend
        balance roundrobin
        server 269627-web-01 107.23.31.249:80 check
        server 269627-web-02 54.160.108.179:80 check
EOL

sudo systemctl enable haproxy
sudo systemctl start haproxy
sudo systemctl status haproxy
