#!/usr/bin/env bash
# Install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Ensure that HAProxy can be managed via an init script

# Refresh the list of available packages
sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy

# Edit HAProxy configuration
haproxy_config=\
"
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 269627-web-01 107.23.31.249:80 check
    server 269627-web-02 54.160.108.179:80 check
"

# Replace the content of the HAProxy configuration file
echo "$haproxy_config" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

# Allow HAProxy to be run by its init script
echo "ENABLED=1" | sudo tee /etc/default/haproxy > /dev/null

# Restart the HAProxy service
sudo service haproxy restart
