#!/usr/bin/env bash
# Sends 5 ping packets to an IP address given as an argument.
# Prints a message with the correct usage of the script.
# Executes the ping command with 5 packets and the argument.

if [ $# -eq 0 ]
then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
  ping -c 5 "$1"
fi
