#!/usr/bin/env bash
# Ensuring Nginx is set up to listen on all active IPv4 IPs on port 80

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# Restart Nginx to apply the changes
sudo service nginx restart
