#!/usr/bin/env bash
# This script configures Nginx to listen on port 80 and ensures it is running.

# Update package lists
apt update
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# start
sudo service nginx start
