#!/usr/bin/env bash
# Ensure Nginx is configured
# script of task 0 but using less lines
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
kill "$(pgrep 'nginx' | head -1)"
