#!/usr/bin/env bash
# The script does the following things:
# Creates a file /var/run/myscript.pid that stores the script PID.
# Prints "To infinity and beyond" endlessly.
# Prints "I hate the kill command" when it gets a SIGTERM signal.
# Prints "Y U no love me?!" when it gets a SIGINT signal.
# Deletes the file /var/run/myscript.pid and quits when it gets
#+ a SIGQUIT or SIGTERM signal.
# Define a function to remove the file and exit


terminator() {
  rm /var/run/myscript.pid
  exit
}

echo "$$" > /var/run/myscript.pid

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminator' SIGTERM
  trap 'terminator' SIGQUIT
done
