#!/usr/bin/env bash
# Controls the script manage_my_process.
# When given the argument start:
# 1. Runs manage_my_process in the background
# 2. Makes a file with its PID in /var/run/my_process.pid
# 3. Prints "manage_my_process started"
# When given the argument stop:
# 1. Stops manage_my_process
# 2. Removes the file /var/run/my_process.pid
# 3. Prints "manage_my_process stopped"
# When given the argument restart:
# 1. Stops manage_my_process
# 2. Removes the file /var/run/my_process.pid
# 3. Runs manage_my_process in the background
# 4. Makes a file with its PID in /var/run/my_process.pid
# 5. Prints "manage_my_process restarted"
# If any other or no arguments are given, prints
# #+ "Usage: manage_my_process

if [ "${1}" == "start" ]
then
    ./manage_my_process &
    touch /var/run/my_process.pid
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process started"
elif [ "${1}" == "stop" ]
then
    echo "manage_my_process stopped"
    kill "$(cat /var/run/my_process.pid)"
    rm /var/run/my_process.pid
elif [ "${1}" == "restart" ]
then
    kill "$(cat /var/run/my_process.pid)"
    rm /var/run/my_process.pid
    ./manage_my_process &
    touch /var/run/my_process.pid
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
