#!/usr/bin/env bash
# Use a while loop with true condition to create an infinite loop
# Print the message To infinity and beyond
#+ Wait for 2 seconds before repeating the loop

while true
do
  echo "To infinity and beyond"
  sleep 2
done
