#!/usr/bin/env bash
# This is a script that prints Fizz, Buzz, FizzBuzz
# or the number depending on the divisibility by 3, 5 or both
#fizzbuzz stuf

counter=1
while [ $counter -ne 101 ]
do
    if [ $((counter % 15)) -eq 0 ]
    then
	echo "FizzBuzz"
    elif [ $((counter % 3)) -eq 0 ]
    then
	echo "Fizz"
    elif [ $((counter % 5)) -eq 0 ]
    then
        echo "Buzz"
    else
	echo $counter
    fi
    ((counter++))
done
