#!/usr/bin/env bash
# This script creates a fictional story using the data from the /etc/passwd file.
# It uses a while loop to read each line of the file and assign the fields to variables
while IFS=':' read -r username password uid gid info home shell; do
  echo "The user $username is part of the $gid gang,"\
  "lives in $home and rides $shell."\
  "$uid's place is protected by the passcode $password,"\
  "more info about the user here: $info"
done < "/etc/passwd"
