#!/usr/bin/env bash
# This script is displaying "Best School" 10 times but prints Hi at 9
# Initialize a counter
count=0
while ((count < 10))
do
	echo "Best School"
	((count++))
	if [ $count -eq 9 ]
	then
		echo "Hi"
	fi
done
