#!/usr/bin/env bash
# This script is displaying "Best School" 10 times but prints Hi at 9
# Initialize a counter
count=0
while ((count < 10))
do
	((count++))
	if [ $count -eq 4 ]
	then
		echo "bad luck"
	elif [ $count -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
done
