#!/usr/bin/env bash
# This script configures the system to resolve localhost,
# to 127.0.0.2 and facebook.com to 8.8.8.8

# Add localhost alias
if ! grep -q "127.0.02" /etc/hosts; then
    echo "127.0.0.2 localhost" >> /etc/hosts
fi

# Add facebook.com alias to 8.8.8.8
if ! grep -q "facebook.com" /etc/hosts; then
    echo "8.8.8.8 facebook.com" >> /etc/hosts
fi