#!/usr/bin/env bash
# This script displays all active IPv4 IPs on the machine

# Using hostname command to get the IP address
hostname -I | tr ' ' '\n' | grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}"
# The hostname command returns the IP address of the machine, but it also returns the loopback address (
# ip -4 addr show | grep -oP '(?<=inet\s)\d+(\.\d+){3}'