#!/usr/bin/env bash

# Update the 'user' directive in the nginx.conf file
sed -i '/^user /c\user nginx;' /etc/nginx/nginx.conf

# Update the 'listen' directive in the default site configuration file
sed -i 's/listen[[:space:]]*80;/listen 8080;/' /etc/nginx/sites-enabled/default

# Update the 'listen' directive for IPv6 in the default site configuration file
sed -i 's/listen[[:space:]]*\[::\]:80;/listen [::]:8080;/' /etc/nginx/sites-enabled/default

# Restart the nginx service
service nginx restart
